### ISSUE TITLE
Running CCS: unsupported sequencing chemistry combination

### ISSUE THREAD

**Issue by polarbe** [SziKayLeung/Whole_Transcriptome_Paper#1]
Hello,

I was trying to run CCS on .bam files fetched from SRA.

I've just run into the following error.
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/28649686/142987700-87c18bd7-3feb-4a23-baef-6508d6eb0bdc.png">

There was no error msg for the isoseq tutorial bam file (alz.1perc.subreads.bam)

As I searched, the bindingkit-sequencingkit-basecallerversion combination described in the error msg is not in the supported combination list in ChemistryTable.cpp file in pbbam v1.7.0 (https://github.com/PacificBiosciences/pbbam/blob/develop/src/ChemistryTable.cpp).

Was it deprecated for the latest version? Should I downgrade pbbam or specify configurations for CCS program?

Could you let me know the exact requirements to run the scripts? 

Any help would be appreciated!

**Comment by SziKayLeung** [comment]
Hello @polarbe, 

Thanks for using our datasets! Some of the fetal samples were generated using an [older chemistry kit](https://github.com/SziKayLeung/Whole_Transcriptome_Paper/blob/main/IsoSeq_Processing/Human/All_Batch_Processing_OldChem.sh) so I've had to downgrade the ppbam version to ccs 3.4.1. The command to run the ccs is then exactly the same:  ccs <input>.subreads.bam  <output>.ccs.bam --minPasses=1. For all the other samples with newer chemistry, ccs was generated with the newer version (ccs 5.0.0).  

Were you planning on rerunning all the samples, or just a few - I can double check which of the SRA samples were generated with the old chemistry kit. 

Best, 
Szi Kay 

P.S I am also happy to share the CCS files/already downstream files generated

**Comment by polarbe** [comment]
@SziKayLeung Thanks a lot for your quick reply!

As you explained, the pipeline works with AdultA (SRR12660779) bam file!
I'll separate the rest of samples by reading .bam header and run the downstream with proper version of programs.
Thank you for your advice.

Could you share the intermediate files before/after minimap2 alignment? I just want to check the processing I did is right.

Best,
polar

**Comment by MenglinC** [comment]
> Hello,
> 
> I was trying to run CCS on .bam files fetched from SRA.
> 
> I've just run into the following error. <img alt="image" width="1176" src="https://user-images.githubusercontent.com/28649686/142987700-87c18bd7-3feb-4a23-baef-6508d6eb0bdc.png">
> 
> There was no error msg for the isoseq tutorial bam file (alz.1perc.subreads.bam)
> 
> As I searched, the bindingkit-sequencingkit-basecallerversion combination described in the error msg is not in the supported combination list in ChemistryTable.cpp file in pbbam v1.7.0 (https://github.com/PacificBiosciences/pbbam/blob/develop/src/ChemistryTable.cpp).
> 
> Was it deprecated for the latest version? Should I downgrade pbbam or specify configurations for CCS program?
> 
> Could you let me know the exact requirements to run the scripts?
> 
> Any help would be appreciated!

Hi,I am new here!Could you please tell me how to convert the .sra files to .bam in your pipeline?
