### ISSUE TITLE
GTF file

### ISSUE THREAD

**Issue by cnk113** [SziKayLeung/Whole_Transcriptome_Paper#2]
Hello,

I was wondering if I can get the GTF file?

Best,
Chang

**Comment by JosephLalli** [comment]
Same - this would be a very helpful resource, and should be small enough to put on github.

**Comment by SziKayLeung** [comment]
Hello @cnk113 and @JosephLalli, 

Sorry for the late reply. 

I've deposited the gtf and other relevant files from the paper to Zenodo, which can be downloaded through: https://zenodo.org/record/7611814#.Y-DzwnbP2Ul. 

For any other specific queries, feel free to also email me on S.K.Leung@exeter.ac.uk.
