### ISSUE TITLE
How to analyze ONT cDNA data with Pychopper/Pinﬁsh pipeline

### ISSUE THREAD

**Issue by WQQIGDB** [SziKayLeung/Whole_Transcriptome_Paper#3]
I'm analyzing ONT cDNA date with Pychopper/Pinﬁsh pipeline and have some questions about the usage of this pipeline.
First, the dataset I used is from SRA archive (as indicated in screenshoot 1). I think this is a clean dataset and did nothing but unzipped to 'clean.fq' being as input file for Pychopper analysis. Should the dataset here be further processed before Pychopper analysis?
Second, I modified the `minimum_cluster_size: 1` in config.yml to preserve the low abundance transcripts. Upon that, I identified the desired transcripts with only one mapped read for each (as indicated in screenshoot 2). Is it reasonable to modify this parameter like this? If so, should such transcripts with one read be reliable full-length transcripts?
Lastly, the Pinfish pipeline has been deprecated on GitHub. I don't know the exact differences between Pinfish and the newly-developed EPI2ME (https://github.com/epi2me-labs/wf-transcriptomes) application. Is that OK if I continue using the Pinfish to identify the full-length transcripts and isoforms?
Hopefully I can get your suggestions!
![SRA achive data](https://github.com/SziKayLeung/Whole_Transcriptome_Paper/assets/152985243/43a7a414-e1ed-4942-8ae3-1fac0d7894bc)
![igv_snapshot](https://github.com/SziKayLeung/Whole_Transcriptome_Paper/assets/152985243/1bad0ce0-4dc4-4e2b-8ccb-4a226980f7fa)

**Comment by SziKayLeung** [comment]
Hello @WQQIGDB, 

1/ The dataset from SRA archive is the ONT raw data so will need to be further processed by Pychopper or equivalent software to remove ONT barcodes and primers. 

2/ With regards to reducing the minimum_cluster_size to 1 read, it depends what the research question is. If it’s a discovery dataset, you could lower the threshold to 1 read on the caveat that you will have a lot of noise with more false positives. I would personally not trust transcripts with only 1 ONT read. 

3/ Epi2me pipeline is more developed/appropriate now than the pinfish/pychopper combination. I have personally not used the Epi2me pipeline so cannot comment too much, but I would think that the Epi2me would be more robust and stringent. You could try and compare both pipelines?  Applying pychopper is good, even if already applied before as long as the adaptor sequence has not been trimmed off the data. It will help orientate the data. Can be left out though if they find that the number of transcripts identified is low (if the data actually has been trimmed). 

I hope that is helpful
